#!/usr/bin/perl
# SPDX-License-Identifier: GPL-2.0-or-later
# vim: ai ts=4 sts=4 et sw=4
#
# Director mailserver pool monitoring script, meant to roughly duplicate the
# functionality of node health monitors on dedicated load-balancers like LVS or
# F5 BigIP LTM. This script can be safely run on more than one director host
# simultaneously, although differences in node reachability may result in
# mailserver vhost count flapping.
#
# Consult the help text for more details on functionality.
#
# Brandon Davidson <brad@oatmail.org>
#
### License:
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
###

use strict;
use warnings;
use Fcntl qw(:flock);
use Getopt::Long;
use IO::Socket::SSL;
use IO::Socket::UNIX;
use POSIX qw(setsid strftime);
use Sys::Syslog qw( :DEFAULT setlogsock);
use Net::DNS;

$SIG{'PIPE'} = 'IGNORE';

my @PORTS;
my @SSL_PORTS;
my $SSL_VERIFY = 1;
my $DEBUG    = 0;
my $NOFORK   = 0;
my $DRY_RUN  = 0;
my $TIMEOUT  = 5;
my $INTERVAL = 30;
my $PIDOPEN  = 0;
my $ORIGPID  = 0;
my $PIDFH;
my $PIDFILE  = '/var/run/poolmon.pid';
my $LOGFILE  = '/var/log/poolmon.log';
my $DIRECTOR = '/var/run/dovecot/director-admin';
my $CREDFILE = '';
my $USERNAME = '';
my $PASSWORD = '';
my $LMTP_FROM = '';
my $LMTP_TO = '';

Getopt::Long::Configure("bundling");
GetOptions('p|port=s'     => \@PORTS,
           's|ssl=s'      => \@SSL_PORTS,
           'v|ssl-verify=i'      => \$SSL_VERIFY,
           'd|debug'      => \$DEBUG,
           't|timeout=i'  => \$TIMEOUT,
           'l|logfile=s'  => \$LOGFILE,
           'k|lockfile=s' => \$PIDFILE,
           'i|interval=i' => \$INTERVAL,
           'f|foreground' => \$NOFORK,
           'n|dry-run'    => \$DRY_RUN,
           'S|socket=s'   => \$DIRECTOR,
           'h|help|?'     => \&help,
           'c|credfile=s' => \&opt_credfile,
           'lmtp-from=s'  => \$LMTP_FROM,
           'lmtp-to=s'    => \$LMTP_TO,
    ) or help();

unless (@PORTS || @SSL_PORTS){
    @PORTS = qw(110 143);
}

validate_port_options('--port', \@PORTS);
validate_port_options('--ssl', \@SSL_PORTS);

if ($TIMEOUT < 1) {
    write_err("Timeout must be at least 1 second");
    exit(1);
}
if ($INTERVAL < 1) {
    write_err("Interval must be at least 1 second");
    exit(1);
}

check_pidfile();
unless($NOFORK){
    daemonize();
} else {
    # Disable buffering of stdout when running in foreground mode
    my $ofh = select STDOUT;
    $| = 1;
    select $ofh;

    # Set up PID file and signal handlers for foreground mode
    $PIDOPEN = 1;
    $ORIGPID = $$;
    print $PIDFH "$$\n";
    $SIG{'INT'} = sub {
        $DEBUG && write_log("Caught signal INT");
        remove_pidfile();
        exit(0);
    };
    $SIG{'TERM'} = sub {
        $DEBUG && write_log("Caught signal TERM");
        remove_pidfile();
        exit(0);
    };
    $SIG{'HUP'} = sub {
        write_log("Reloading credentials");
        load_credentials();
    };
}

while(1){
    scan_host_loop();
    sleep($INTERVAL);
}
exit(0);

### It's subroutines, all the way down.

# Print help text and exit
sub help {
    print "Usage: $0 [<args>]
Retrieves a set of mailserver hosts from a Dovecot director and performs
parallel checks against a list of ports.

If any port on a host cannot be connected to or fails to present a banner line
within the timeout period, that host is disabled by setting its status to
'down', and flushing active mappings from that host. If a disabled host passes
all host checks, its status is restored to 'up'.

Arguments:
  -d, --debug           Show additional logging (default: false)
  -f, --foreground      Run in foreground (default: false)
  -n, --dry-run         Just log proposed actions (default: false)
  -h, --help            This text
  -i, --interval=SECS   Scan interval in seconds (default: 30)
  -k, --lockfile=PATH   PID/lockfile location (default: /var/run/poolmon.pid)
  -l, --logfile=PATH    Log file location (default: /var/log/poolmon.log)
                        Set to 'syslog' for writing to local syslog socket
  -p, --port=PORT       Port to check; repeat for multiple (default: 110, 143)
  -v  --ssl-verify=(0|1) Set to 1 to enable, 0 to disable SSL_VERIFY
  -s  --ssl=PORT        Port with SSL/TLS; repeat for multiple (default: none)
                        If the port is recognized as common IMAP or POP3 port,
                        health checks will look for a valid connect banner.
                        You can force a protocol (IMAP or POP3) by specifying
                        it before the port, separated by a colon. Example:
                          --port POP3:110 --ssl IMAP:993
  -c  --credfile=PATH   File with credentials to authenticate as, mode 0600.
                          - Username on 1st line.
                          - Password on 2nd line.
                        (default: health checks will not attempt authentication)
  --lmtp-from=ADDR      Sender e-mail address for LMTP
  --lmtp-to=ADDR        Recipient e-mail address for LMTP
  -S, --socket=PATH     Path to Dovecot director-admin socket
                        (default: /var/run/dovecot/director-admin)
  -t, --timeout=SECS    Port health check timeout in seconds (default: 5)
";
    exit(1);
}

sub validate_port_options {
    my ($opt_name, $ports_ref) = @_;
    foreach my $entry (@{$ports_ref}) {
        my $port;
        if ($entry =~ /^(?:IMAP|POP3|LMTP):(\d+)$/i) {
            $port = $1;
        } elsif ($entry =~ /^(\d+)$/) {
            $port = $1;
        } else {
            write_err("Invalid $opt_name value '$entry': must be numeric or PROTO:PORT (IMAP|POP3|LMTP)");
            exit(1);
        }

        if ($port < 1 || $port > 65535) {
            write_err("Invalid $opt_name value '$entry': port must be in range 1-65535");
            exit(1);
        }
    }
}

# Get list of mailservers from local director and scan them
sub scan_host_loop {
    # Get mailserver list
    my $sock = director_connect() || return;
    my @lines;
    my %CHILDREN;
    print $sock "HOST-LIST\n";
    while(my $line = readline($sock)){
        last if $line eq "\n";
        chomp $line;
        push(@lines, $line);
    }
    close($sock);
    undef($sock);
    $DEBUG && write_log('Director returned ',scalar(@lines),' hosts');

    # Start host scans
    foreach my $line (@lines){
        if(my ($host, $weight, $clients, $tag, $updown) = split("\t", $line)){
            my $pid = fork();
            if ($pid == 0) {
                close($PIDFH) if $PIDFH;
                exit(scan_host($host));
            } elsif ($pid > 0) {
                $CHILDREN{$pid} = [$host, $updown];
            } else {
                write_err("Failed to fork scan process for host $host: $!");
            }
        }
    }

    # Take action based on check results returned by subprocesses
    while(keys %CHILDREN){
        my $pid = waitpid(-1, 0);
        if ($pid == -1) {
            last unless $!{EINTR};
            next;
        }
        my $OK = $? >> 8;
        my ($host, $updown) = @{$CHILDREN{$pid}};
        $DEBUG && write_log("Scan of host $host with status $updown by PID $pid exited with status $OK");
        if ($OK) { # Enable host if currently disabled (updown=D)
            enable_host($host) if $updown eq "D";
            $DEBUG && write_log("Set host $host to enabled");
        } else {  # Disable host if currently enabled (updown=U)
            disable_host($host) if $updown eq "U";
            $DEBUG && write_log("Set host $host to disabled");
        }
        delete($CHILDREN{$pid});
    }
    $DEBUG && write_log('Host scans complete');
}

# Connect to local director and perform version handshake
sub director_connect {
    my $HANDSHAKE = "VERSION\tdirector-doveadm\t1\t0\n";
    my $sock = IO::Socket::UNIX->new($DIRECTOR);
    if ($sock) {
        print $sock $HANDSHAKE;
        unless (readline($sock) eq $HANDSHAKE){
            write_err("Director handshake failed!");
            close($sock);
            return undef;
        }
    } else {
        write_err("Failed to connect to director: $!");
    }
    return $sock;
}

# Scan all ports on a given host. 1 == success. 0 == failure
sub scan_host {
    my ($host) = @_;
    my $OK = eval {
        _scan_host_impl($host);
    };
    if ($@) {
        write_err("Unexpected error scanning $host: $@");
        return 0;
    }
    return $OK ? 1 : 0;
}

sub _scan_host_impl {
    my ($host) = @_;
    my $OK = 1;
    my $hostname;
    my $resolver = Net::DNS::Resolver->new();
    my $reply = $resolver->query($host);
    if ($reply) {
        foreach my $rr ($reply->answer) {
            next unless $rr->type eq 'PTR';
            if (defined $hostname) {
                $DEBUG && write_log("Multiple PTR records for $host. Ignoring all but one.");
                last;
            }
            # Remove trailing .
            $hostname = substr($rr->rdatastr, 0, -1);
        }
    }
    else {
        $DEBUG && write_log("PTR lookup failure for $host");
    }
    # Check non-SSL ports first
    foreach my $port (@PORTS){
        if (! scan_port($host, $port, 0, $hostname)){
            sleep(3);
            my $retry_ok = 0;
            for (my $i = 0; $i < 4; $i++) {
                select(undef, undef, undef, 0.5) if $i > 0;
                if (scan_port($host, $port, 0, $hostname)){
                    $retry_ok = 1;
                    last;
                }
            }
            $OK = 0 unless $retry_ok;
        }
    }
    # Skip SSL checks if standard checks indicated failure
    return 0 unless $OK;
    foreach my $port (@SSL_PORTS){
        if (! scan_port($host, $port, 1, $hostname)){
            sleep(3);
            my $retry_ok = 0;
            for (my $i = 0; $i < 4; $i++) {
                select(undef, undef, undef, 0.5) if $i > 0;
                if (scan_port($host, $port, 1, $hostname)){
                    $retry_ok = 1;
                    last;
                }
            }
            $OK = 0 unless $retry_ok;
        }
    }
    return $OK;
}

# Check a port on a host, with optional SSL and login
sub scan_port {
    my $host         = shift || return;
    my $port         = shift || return;
    my $ssl          = shift;
    my $ssl_hostname = shift;
    my $prot;
    my $ret;

    #$IO::Socket::SSL::DEBUG = 3;

    ($port, $prot) = get_port_proto($port);
    my $verify_mode = $SSL_VERIFY ? IO::Socket::SSL::SSL_VERIFY_PEER() : IO::Socket::SSL::SSL_VERIFY_NONE();
    my $cn_scheme = ($prot eq 'IMAP') ? 'imap' : ($prot eq 'POP3') ? 'pop3' : 'none';
    my $sock = IO::Socket::SSL->new(PeerAddr => $host,
                                    PeerPort => $port,
                                    Timeout  => $TIMEOUT,
                                    SSL_startHandshake => $ssl,
                                    SSL_verify_mode => $verify_mode,
                                    SSL_verifycn_scheme => $cn_scheme,
                                    SSL_verifycn_name => $ssl_hostname);
    unless ($sock) {
        my $ssl_err = IO::Socket::SSL::errstr() || $@ || 'unknown SSL socket error';
        write_err("Socket creation failed for $host:$port: $ssl_err");
    }

    $ret = eval {
        local $SIG{ALRM} = sub {
            $DEBUG && write_log("Timeout");
            die "Timeout\n";
        };
        alarm $TIMEOUT;
        my $result;
        if ($sock){
            if ($prot eq 'IMAP'){
                $result = scan_imap($host, $port, $sock);
            } elsif ($prot eq 'POP3'){
                $result = scan_pop3($host, $port, $sock);
            } elsif ($prot eq 'LMTP'){
                $result = scan_lmtp($host, $port, $sock);
            } elsif (readline($sock)){
                $DEBUG && write_log("$host:$port Connection OK");
                $result = 1;
            }
        } else {
            $DEBUG && write_log("$host:$port Connection Failed");
            $result = 0;
        }
        alarm 0;
        $result;
    };

    if ($@){
        alarm 0;
        $DEBUG && write_log("$host:$port Read Timeout");
    }

    close($sock) if $sock;
    return $ret;
}

sub scan_imap {
    my $host = shift || return;
    my $port = shift || return;
    my $sock = shift || return;
    my $line = readline($sock);
    return 0 unless defined $line;
    if ($line =~ m/LOGINDISABLED/ && $line !~ m/STARTTLS/){
        write_err("$host:$port IMAP Server Reports Plaintext Login Disabled - check login_trusted_networks");
        return 1;
    } elsif ($line =~ m/^\* OK/){
        if ($USERNAME && $PASSWORD){
            if ($line =~ m/STARTTLS/){
                printf $sock "01 STARTTLS\r\n";
                my $reply = readline($sock);
                unless (defined $reply && $reply =~ m/^01 OK/) {
                    $DEBUG && write_log("$host:$port TLS negotiation failed");
                    return 0;
                }
                unless ($sock->connect_SSL) {
                    $DEBUG && write_log("$host:$port SSL upgrade failed");
                    return 0;
                }
            }
            printf $sock "02 LOGIN %s {%d}\r\n%s\r\n", $USERNAME, length($PASSWORD), $PASSWORD;
            my $literal = readline($sock);
            my $logstat = readline($sock);
            if (defined $literal && $literal =~ m/^\+/ && defined $logstat && $logstat =~ m/^02 OK/){
                $DEBUG && write_log("$host:$port IMAP Login OK");
                printf $sock "03 LOGOUT\r\n";
                return 1;
            } else {
                $DEBUG && write_log("$host:$port IMAP Login Failed");
                $DEBUG && write_log("\t\t" . ($logstat // '(no response)'));
                printf $sock "03 LOGOUT\r\n";
                return 0;
            }
        } else {
            printf $sock "01 LOGOUT\r\n";
            $DEBUG && write_log("$host:$port IMAP Banner OK");
            return 1;
        }
    } else {
        $DEBUG && write_log("$host:$port IMAP Banner Check Failed");
        return 0;
    }
}

sub scan_pop3 {
    my $host = shift || return;
    my $port = shift || return;
    my $sock = shift || return;
    my $line = readline($sock);
    return 0 unless defined $line;
    if ($line =~ m/\+OK/){
        if ($USERNAME && $PASSWORD){
            printf $sock "USER %s\r\n", $USERNAME;
            my $userval = readline($sock);
            unless (defined $userval) {
                $DEBUG && write_log("$host:$port POP3 USER command returned no response");
                printf $sock "QUIT\r\n";
                return 0;
            }
            if ($userval =~ m/^-ERR Plaintext authentication disallowed/){
                write_err("$host:$port POP3 Server Reports Plaintext Login Disabled - check login_trusted_networks");
                printf $sock "QUIT\r\n";
                return 1;
            } elsif ($userval =~ m/^\+OK/){
                printf $sock "PASS %s\r\n", $PASSWORD;
                my $logstat = readline($sock);
                unless (defined $logstat) {
                    $DEBUG && write_log("$host:$port POP3 PASS command returned no response");
                    printf $sock "QUIT\r\n";
                    return 0;
                }
                if ($logstat =~ m/^\+OK/){
                    $DEBUG && write_log("$host:$port POP3 Login OK");
                    printf $sock "QUIT\r\n";
                    return 1;
                } else {
                    $DEBUG && write_log("$host:$port POP3 Login Failed");
                    $DEBUG && write_log("\t\t$logstat");
                    printf $sock "QUIT\r\n";
                    return 0;
                }
            } else {
                $DEBUG && write_log("$host:$port POP3 USER command failed");
                $DEBUG && write_log("\t\t$userval");
                printf $sock "QUIT\r\n";
                return 0;
            }
        } else {
            $DEBUG && write_log("$host:$port POP3 Banner OK");
            printf $sock "QUIT\r\n";
            return 1;
        }
    } else {
        $DEBUG && write_log("$host:$port POP3 Banner Check Failed");
        return 0;
    }
}

sub scan_lmtp {
    my $host = shift || return;
    my $port = shift || return;
    my $sock = shift || return;
    my $line = readline($sock);
    return 0 unless defined $line;
    if ($line =~ m/^2\d\d[ -]/){
        # Send LHLO greeting before any commands
        printf $sock "LHLO %s\r\n", "poolmon";
        my $lhloreply = readline($sock);
        unless (defined $lhloreply && $lhloreply =~ m/^2\d\d/){
            write_err("$host:$port LMTP LHLO rejected");
            return 0;
        }
        # Read any continuation lines (multi-line response)
        while (defined $lhloreply && $lhloreply =~ m/^2\d\d-/) {
            $lhloreply = readline($sock);
        }
        if ($LMTP_TO){
            printf $sock "MAIL FROM:<%s>\r\n", $LMTP_FROM;
            my $mailreply = readline($sock);
            unless (defined $mailreply && $mailreply =~ m/^2\d\d /){
                write_err("$host:$port LMTP Server Rejects sender address");
                return 0;
            }

            printf $sock "RCPT TO:<%s>\r\n", $LMTP_TO;
            my $rcptreply = readline($sock);
            unless (defined $rcptreply && $rcptreply =~ m/^2\d\d /){
                write_err("$host:$port LMTP Server Rejects recipient address");
                return 0;
            }

            $DEBUG && write_log("$host:$port LMTP OK");
            printf $sock "QUIT\r\n";
            return 1;
        } else {
            $DEBUG && write_log("$host:$port LMTP Banner OK");
            printf $sock "QUIT\r\n";
            return 1;
        }
    } else {
        $DEBUG && write_log("$host:$port LMTP Banner Check Failed");
        return 0;
    }
}

# Extract port and protocol from combined port command-line option
sub get_port_proto {
    my $port = shift;

    if ($port =~ m/IMAP:(\d+)/i){
        return $1, 'IMAP';
    } elsif ($port =~ m/POP3:(\d+)/i){
        return $1, 'POP3';
    } elsif ($port =~ m/LMTP:(\d+)/i){
        return $1, 'LMTP';
    } elsif ($port == 143 || $port == 993){
        return $port, 'IMAP';
    } elsif ($port == 110 || $port == 995){
        return $port, 'POP3';
    } elsif ($port == 24){
        return $port, 'LMTP';
    } else {
        return $port, 'UNKNOWN';
    }
}

# Mark host down and flush associations
# Note that there's no way to kill active sessions, they'll have to time out
# on their own.
sub disable_host {
    my $host = shift || return;
    unless($DRY_RUN){
        my $sock = director_connect() || return;
        print $sock "HOST-DOWN\t$host\n";
        if (readline($sock) eq "OK\n") {
            print $sock "HOST-FLUSH\t$host\n";
            if (readline($sock) ne "OK\n") {
                write_err("Failed to flush $host");
            }
        } else {
            write_err("Failed to mark $host as down");
        }
        close($sock);
        undef($sock);
        write_log("$host disabled");
    } else {
        write_log("DRY-RUN: $host disabled");
    }
}

# Mark host as up
sub enable_host {
    my $host = shift || return;
    unless($DRY_RUN){
        my $sock = director_connect() || return;
        print $sock "HOST-UP\t$host\n";
        if (readline($sock) ne "OK\n") {
            write_err("Failed to mark $host as up");
        }
        close($sock);
        undef($sock);
        write_log("$host enabled");
    } else {
        write_log("DRY-RUN: $host enabled");
    }
}

# Append a line to stdout
sub write_log {
    if ($LOGFILE eq "syslog") {
        write_to_syslog("info", join('', @_));
    } else {
        printf(STDOUT "%s LOG %s\n", strftime("%h %d %H:%M:%S", localtime()), join('', @_));
    }
}

# Append a line to stderr
sub write_err {
    if ($LOGFILE eq "syslog") {
        write_to_syslog("err", join('', @_));
    } else {
        printf(STDERR "%s ERR %s\n", strftime("%h %d %H:%M:%S", localtime()), join('', @_));
    }
}

{
    my $_syslog_opened = 0;
    sub write_to_syslog {
        my ($priority, $msg) = @_;
        return 0 unless ($priority =~ /info|err|debug/);

        unless ($_syslog_opened) {
            setlogsock("unix");
            openlog("poolmon", "pid,cons", "user");
            $_syslog_opened = 1;
        }
        syslog($priority, "%s", $msg);
        return 1;
    }
}

# Check to see if the pidfile exists and the indicated pid is still running.
# Opens and exclusively locks the pidfile, leaving $PIDFH open to hold the lock.
sub check_pidfile {
    open($PIDFH, '+>>', $PIDFILE) or die "Can't open pidfile $PIDFILE: $!";
    unless (flock($PIDFH, LOCK_EX|LOCK_NB)) {
        seek($PIDFH, 0, 0);
        my $oldpid = readline($PIDFH);
        chomp $oldpid if defined $oldpid;
        write_err("Already running as pid $oldpid");
        exit(1);
    }
    # Also check PID content in case a prior run didn't use flock
    seek($PIDFH, 0, 0);
    my $oldpid = readline($PIDFH);
    if (defined $oldpid) {
        chomp $oldpid;
        if ($oldpid =~ /^\d+$/ && kill(0, $oldpid)) {
            write_err("Already running as pid $oldpid");
            exit(1);
        }
    }
    truncate($PIDFH, 0);
    seek($PIDFH, 0, 0);
}

# Remove the pidfile and exit
sub remove_pidfile {
    return unless $PIDOPEN;
    if ($$ == $ORIGPID) {
        write_log('Shutting down');
        unlink($PIDFILE);
        close($PIDFH);
    }
}

sub opt_credfile {
    my ($opt, $value)= @_;
    if ( -e $value ){
        $CREDFILE = $value;
        load_credentials();
    } else {
        write_err("Credential file '$value' not found!");
        exit(1);
    }
}

sub load_credentials {
    return unless $CREDFILE;
    # Check permissions on credentials file
    if ((stat($CREDFILE))[2] & 077){
        write_err("Credential file $CREDFILE must be chmod 600");
        exit(1);
    }
    if(open(my $credfh, '<', $CREDFILE)){
        $USERNAME = readline($credfh);
        $PASSWORD = readline($credfh);
        close($credfh);
        chomp($USERNAME);
        chomp($PASSWORD);
        if ($USERNAME && $PASSWORD){
            $DEBUG && write_log("Loaded credentials from $CREDFILE");
        } else {
            write_err("Could not read username and password from $CREDFILE");
        }
    } else {
        write_err("Could not open credential file: $!");
    }
}



# Fork into background and write pidfile
sub daemonize {
    # PID file already opened and locked in check_pidfile()
    # Register cleanup handlers before forking
    $PIDOPEN = 1;
    $ORIGPID = $$;
    $SIG{'INT'} = sub {
        $DEBUG && write_log("Caught signal INT");
        remove_pidfile();
        exit(0);
    };
    $SIG{'QUIT'} = sub {
        $DEBUG && write_log("Caught signal QUIT");
        remove_pidfile();
        exit(0);
    };
    $SIG{'TERM'} = sub {
        $DEBUG && write_log("Caught signal TERM");
        remove_pidfile();
        exit(0);
    };

    # Disconnect from terminal and session
    chdir('/')         or die "Can't chdir to /: $!";
    umask(0022);
    open(STDIN, '<', '/dev/null')  or die "Can't read /dev/null: $!";
    if ($LOGFILE ne "syslog") {
        open(STDOUT, '>>', $LOGFILE) or die "Can't write to $LOGFILE: $!";
        open(STDERR, '>>', $LOGFILE) or die "Can't write to $LOGFILE: $!";
    }
    defined(my $pid = fork())  or die "Can't fork: $!";
    if ($pid) {
        # Child process becomes the pidfile owner; parent exits without cleanup.
        $PIDOPEN = 0;
        exit(0);
    }
    $ORIGPID = $$;
    setsid()           or die "Can't start a new session: $!";

    # Write forked PID to pidfile; keep $PIDFH open to maintain exclusive lock
    write_log("Forked to background as PID $$");
    print $PIDFH "$$\n";

    # Reopen logfiles on HUP
    $SIG{'HUP'} = sub {
        if ($LOGFILE ne "syslog") {
          open(STDOUT, '>>', $LOGFILE) or die "Can't reopen $LOGFILE: $!";
          open(STDERR, '>>', $LOGFILE) or die "Can't reopen $LOGFILE: $!";
        }
        write_log("Logfile reopened");
        load_credentials();
    }
}

# Ensure pidfile cleanup on exit
END {
    remove_pidfile();
}
